import type { Question } from './types'

// CeMAP 1's own "Unit 2 – Specimen Paper C", reproduced as an ORIGINAL supplied mock exam.
// Answers verified against CeMAP_1__Delegate_2026.pdf, "ANSWERS" section, "UNIT 2 - SPECIMEN PAPER C".

function sq(n: number, text: string, options: string[], correctIndex: number, explanation: string): Question {
  return {
    id: `c1-u2-specC-q${n}`, module: 'cemap1', unitKey: 'unit2', topicKey: 'specimen-c',
    text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: 'CeMAP 1, Unit 2 Specimen Paper C', origin: 'original'
  }
}

export const unit2SpecimenPaperC: Question[] = [
  sq(1,'Abi must carry out an appropriateness test on a client\u2019s transaction. This is because:',
    ['Abi is not yet fully competent to give advice on investments', 'Abi is uncertain that her advice is correct', 'The transaction is for an insistent client', 'The transaction is for derivatives on an execution-only basis'],3,
    'Complex products like derivatives require an appropriateness test when sold on an execution-only basis.'),
  sq(2,'Which is an important part of the listening process during a client interview?',
    ['Acknowledging', 'Agreeing', 'Questioning', 'Speaking'],0,
    'Acknowledging that a message has been received and understood is central to active listening.'),
  sq(3,'According to Albert Mehrabian\u2019s research, what percentage of communication of feelings and attitudes is conveyed by the actual words said?',
    ['7%', '38%', '55%', '80%'],0,
    'Mehrabian\u2019s research found only 7% is conveyed by the words themselves, with the rest via tone (38%) and facial expression (55%).'),
  sq(4,'A client becomes frustrated because his adviser keeps asking for information already given. The most likely reason is that the adviser is:',
    ['Asking mainly closed questions', 'Asking mainly open questions', 'Not listening to the client', 'Summarising too often'],2,
    'Failing to actually listen and retain what a client has already said is the most likely explanation for repeating questions.'),
  sq(5,'Sunita is asked to advise on several products but is not competent in all areas. What should she do for the areas she isn\u2019t competent in?',
    ['Cease dealing with the client immediately', 'Refer the client to a suitably qualified colleague for those areas', 'Give the advice but with a disclaimer', 'Persuade the client those areas aren\u2019t important'],1,
    'Referring the client to a colleague with the right expertise ensures the client still receives suitable, competent advice.'),
  sq(6,'Which is NOT specified by the FCA as a driver of vulnerability?',
    ['Capability', 'Health', 'Lifestyle', 'Resilience'],2,
    'The FCA\u2019s four drivers are health, life events, resilience and capability — "lifestyle" is not one of them.'),
  sq(7,'Which form of CPD is NOT considered structured learning?',
    ['Attending conferences', 'Attending training courses', 'Completing appropriate e-learning', 'Researching products for clients'],3,
    'Researching products/services is considered unstructured learning, unlike courses, conferences and e-learning with defined outcomes.'),
  sq(8,'The FOS recommends compensation exceeding the maximum rules-based amount for a personal pension case. What is the position?',
    ['Either party can refer the case to the Pensions Ombudsman for a second ruling', 'The award is binding in full on the firm and the customer', 'The award cannot exceed the limit in any circumstances', 'The firm can refuse to pay the full amount but the customer can take the matter to court'],3,
    'The FOS can recommend a higher figure, but the firm is only bound up to the standard limit — the customer can pursue any excess through the courts instead.'),
  sq(9,'A judgement made by the Financial Ombudsman Service is binding on:',
    ['The consumer only', 'The firm only', 'The firm and the consumer', 'Neither the firm nor the consumer'],1,
    'FOS decisions bind the firm but not the consumer, who can still pursue the matter in court.'),
  sq(10,'Which is classified as special category data under data protection regulations?',
    ['Date of birth', 'Marital status', 'Political persuasion', 'Salary'],2,
    'Political persuasion is one of the special (sensitive) categories requiring consent to process.'),
  sq(11,'Where an insurance company defaulted and couldn\u2019t settle a claim, the FSCS would pay 90% of a claim for:',
    ['Employer liability insurance', 'Payment protection insurance', 'Third party motor insurance', 'Travel insurance'],3,
    'Travel insurance falls outside the 100%-protected categories (pure protection, long-term care, annuities, compulsory insurances), so only 90% cover applies.'),
  sq(12,'A firm receives a complaint that cannot be resolved within three days. It must issue an acknowledgement:',
    ['Promptly', 'Within two working days', 'Within three working days', 'Within five working days'],0,
    'An acknowledgement must be sent promptly where a complaint isn\u2019t resolved within 3 business days.'),
  sq(13,'Allan received pension advice 7 years ago; information suggesting bad advice came to light 2 years ago. Within what maximum further period must he complain?',
    ['He is unable to complain, already out of time', 'One year', 'Two years', 'Three years'],1,
    'With 2 of the 3-years-from-awareness window already elapsed, Allan has 1 year remaining to complain.'),
  sq(14,'Which client category receives the LOWEST level of customer protection?',
    ['Eligible counterparty', 'Professional client', 'Retail client', 'Professional counterparty'],0,
    'Eligible counterparties, being highly sophisticated organisations, receive the lowest level of protection.'),
  sq(15,'Which is TRUE regarding execution-only business?',
    ['A client declining advice and choosing another product is classed as execution-only', 'A firm can fully protect itself in an FCA investigation via a general disclaimer', 'The adviser may provide information/advice but cannot give a recommendation', 'The adviser\u2019s duty to fully explain the product/risks does not apply'],3,
    'On a genuine execution-only basis, the adviser is not required to give the full suitability-related explanation of the product and its risks.'),
  sq(16,'Which FCA customer category would usually apply to a collective investment fund seeking straightforward execution of transactions?',
    ['Eligible counterparty', 'Professional client', 'Retail client', 'Private client'],0,
    'A sophisticated fund undertaking simple execution-type dealing is typically classed as an eligible counterparty.'),
  sq(17,'When making a recommendation, a firm must ensure it is:',
    ['Affordable only', 'Both suitable and affordable', 'Suitable and competitively priced', 'Suitable only'],1,
    'A recommendation must be both suitable for the client\u2019s needs and affordable for them.'),
  sq(18,'Where a firm offers independent financial advice, it is NOT an FCA requirement that the advice is:',
    ['Comprehensive', 'Fair', 'Free from all charges', 'Unbiased'],2,
    'Independent advice must be comprehensive, fair and unbiased — but there is no requirement that it be free of all charges.'),
  sq(19,'After a full fact find, none of the providers on an IFA\u2019s panel offers a suitable product. What is the position?',
    ['No recommendation can be made', 'The client must be referred to an adviser who can find a suitable product', 'The client must choose an alternative on an execution-only basis', 'The IFA can use products from other providers if it is in the client\u2019s best interests'],3,
    'To maintain genuine independence and suitability, the IFA can go outside its usual panel where necessary for the client\u2019s best interests.'),
  sq(20,'Which is true of an adviser\u2019s Statement of Professional Standing (SPS)?',
    ['It can be validated by the firm', 'It is issued by the FCA', 'It is valid for 12 months', 'It must be shown to clients on first contact'],2,
    'An SPS is valid for 12 months, issued by an accredited body — not the firm itself or the FCA — and doesn\u2019t need to be shown to clients.'),
  sq(21,'The FCA\u2019s regulatory sandbox enables firms to:',
    ['Collaborate on technology with other firms', 'Discuss regulatory issues with FCA advisers without prejudice', 'Help the FCA establish new rules', 'Test new services and products without regulatory risks'],3,
    'The sandbox lets firms trial innovative products/services in a controlled environment without the full weight of regulatory sanction.'),
  sq(22,'In relation to business ethics:',
    ['Acting within regulations ensures ethical behaviour', 'Ethical failure is always the result of malevolent acts', 'Ethical standards are set out in the detailed FCA rules', 'High ethical standards can be compatible with profit'],3,
    'Ethical behaviour and profitability are not mutually exclusive — merely following minimum regulatory requirements does not by itself constitute genuine ethical behaviour.'),
  sq(23,'Which is FALSE in relation to whistleblowing?',
    ['It\u2019s a facility operated by the FCA', 'It relates to information about wrongdoing', 'The whistleblower must provide evidence to prove wrongdoing', 'Whistleblowers will remain anonymous'],2,
    'The FCA stresses whistleblowers only need to report their concerns — they do NOT need to prove wrongdoing themselves.'),
  sq(24,'Good communication skills include all of the following EXCEPT:',
    ['Demonstrating sound technical knowledge', 'Explaining complex information in a way the customer can understand', 'Listening to what the customer is saying', 'Writing reports full of technical phrases'],3,
    'Jargon-heavy reports work against good communication, which should be clear and accessible.'),
  sq(25,'Davina joined as a trainee mortgage adviser on 1 May 2025. What are the requirements for her qualification?',
    ['A Level 3 qualification by 30 April 2028', 'A Level 4 qualification by 30 April 2028', 'A Level 3 qualification by 30 April 2029', 'A Level 4 qualification by 30 April 2028 (duplicate)'],2,
    'Mortgage advisers need a Level 3 qualification within 48 months (4 years) of starting to advise under supervision — 1 May 2025 + 48 months lands on 30 April 2029.'),
  sq(26,'(Case study: Mira meets Lucy, who inherited £400,000, wants access in 5 years for son\u2019s university fees) Which should Mira consider before the meeting? 1. Know your customer, 2. IHT planning, 3. AML issues, 4. Fair treatment of customers, 5. Distance Marketing Regulations.',
    ['1, 2 and 3 only', '1, 2 and 4 only', '1, 3 and 4 only', '1, 4 and 5 only'],2,
    'Since this is a face-to-face meeting (not distance marketing) and there\u2019s no indication IHT planning is the specific need, know-your-customer, AML and fair treatment are the most directly relevant considerations.'),
  sq(27,'What should be Mira\u2019s primary objective for the meeting?',
    ['Increase her employer\u2019s profits', 'Increase Lucy\u2019s capital', 'Maximise her fee income', 'Understand Lucy\u2019s needs'],3,
    'Understanding the client\u2019s genuine needs is the foundation of suitable, ethical advice — ahead of any commercial consideration.'),
  sq(28,'Before completing the fact find, Lucy asks if a product she\u2019s seen (guaranteed return, monthly income, 10-year tie-in) is suitable for her. What should Mira do?',
    ['Suggest Lucy complete the application now if happy', 'Explain she cannot recommend anything until she has fully analysed Lucy\u2019s situation', 'State the product is likely to be suitable', 'Suggest Lucy proceed on an execution-only basis'],1,
    'A genuine recommendation cannot be made before the adviser has properly understood the client\u2019s full circumstances.'),
  sq(29,'Assessing the extent to which a loss would affect Lucy\u2019s financial situation is referred to as:',
    ['Attitude to risk', 'Capacity for loss', 'Risk tolerance', 'Risk category'],1,
    'Capacity for loss is the specific, factual assessment of how much loss a client could genuinely absorb.'),
  sq(30,'Which of these would NOT require a suitability report?',
    ['Cash ISA', 'Unit trust', 'Investment trust', 'Personal pension'],0,
    'A cash ISA is not among the products (life/annuities, pensions, unit trusts/investment trusts/OEICs) requiring a suitability report.'),
  sq(31,'(Case study: Bryony advises Betty, recently widowed at 62) Which FCA driver of vulnerability is most likely to apply to Betty?',
    ['Life events due to the bereavement', 'Capability', 'Health', 'Resilience'],0,
    'Bereavement is specifically identified as a "life events" driver of vulnerability.'),
  sq(32,'What is NOT one of the FCA\u2019s specific requirements for firms supporting vulnerable clients like Betty?',
    ['Tell Betty about available help and support options', 'Provide straightforward options for a designated person to act on her behalf', 'Design specific products for clients like Betty', 'Set up in-house teams or third-party links for specialist support'],2,
    'Designing entirely new bespoke products isn\u2019t a specific FCA requirement — the focus is on processes, support and access, not product design.'),
  sq(33,'Bryony, moved by Betty\u2019s story (similar to her own mother\u2019s), wants to discuss Betty\u2019s case with her mother. Which Principle is she in danger of breaching?',
    ['Principle 1 — Integrity', 'Principle 2 — skill, care and diligence', 'Principle 8 — conflicts of interest', 'Principle 12 — the consumer duty'],0,
    'Sharing a client\u2019s confidential case details with an unrelated third party breaches the confidentiality expected under Principle 1 (Integrity).'),
  sq(34,'Regarding Andrew\u2019s request for advice specifically on an interest-only mortgage repayment vehicle, Bryony would be providing:',
    ['Advice to an insistent client', 'Focused advice', 'Simplified advice', 'Regulated advice (generic label)'],1,
    'A personal recommendation limited to Andrew\u2019s specific stated need is focused advice.'),
  sq(35,'Regarding Andrew\u2019s defined benefit occupational pension transfer interest, an appropriate course of action for Bryony is to:',
    ['Seek more information and make a suitable recommendation herself', 'Explain neither she nor the firm can provide advice', 'Explain she will need to refer Andrew to Annette, the pension transfer specialist', 'Suggest Andrew makes the transfer on an execution-only basis'],2,
    'DB pension transfers are complex, specialist advice areas — Bryony should refer Andrew to the firm\u2019s pension transfer specialist, Annette.'),
  sq(36,'(Case study: Kate, mortgage adviser, John wants to borrow £200,000 for a £250,000 property, with some deposit from cash kept at home) Why must Kate verify John\u2019s identification under money laundering regulations?',
    ['He has more than £15,000 in his bank account', 'His employer pays him in cash', 'The deposit will be over €15,000', 'The purpose of the meeting is to borrow money'],2,
    'The AML identity verification threshold is triggered when the transaction (here, the deposit/loan) exceeds €15,000.'),
  sq(37,'Kate could verify John\u2019s address with:',
    ['A letter of declaration by John\u2019s employer', 'John\u2019s most recent bank statement', 'John\u2019s passport', 'John\u2019s recent payslip'],1,
    'A recent bank statement is an acceptable address verification document; a passport verifies identity/name, not address.'),
  sq(38,'If John is found to be laundering money via the mortgage application, he could face imprisonment for up to:',
    ['5 years', '7 years', '10 years', '14 years'],3,
    'Concealing, arranging or acquiring criminal property carries a maximum sentence of 14 years.'),
  sq(39,'Kate suspects John of money laundering and discusses this with her manager. If she then mentions this conversation to John, she could be accused of:',
    ['Acquiring criminal property', 'Conspiracy to commit fraud', 'Financing organised crime', 'Tipping off'],3,
    'Alerting a suspect that they are under suspicion or investigation is the offence of "tipping off".'),
  sq(40,'If Kate suspects John of money laundering, she should report her suspicions to the:',
    ['Firm\u2019s compliance officer', 'Firm\u2019s Money Laundering Reporting Officer', 'Joint Money Laundering Steering Group', 'National Crime Agency'],1,
    'Suspicions must be reported internally to the firm\u2019s Money Laundering Reporting Officer, who then decides whether to escalate to the National Crime Agency.')
]
