import type { Question } from './types'

// These 40 questions are CeMAP 1's own "Unit 1 – Specimen Paper A", reproduced as an
// ORIGINAL supplied mock exam (kept separate from the topic-test question bank in
// questions.ts). Answers are taken directly from the PDF's own answer key
// (CeMAP_1__Delegate_2026.pdf, "ANSWERS" section, "UNIT 1 - SPECIMEN PAPER A").
// Explanations below are written by the app, not copied from the source.

function sq(n: number, text: string, options: string[], correctIndex: number, explanation: string): Question {
  return {
    id: `c1-u1-specA-q${n}`, module: 'cemap1', unitKey: 'unit1', topicKey: 'specimen-a',
    text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: 'CeMAP 1, Unit 1 Specimen Paper A', origin: 'original'
  }
}

export const specimenPaperA: Question[] = [
  sq(1,'Inflation can best be described as being a:',
    ['Fall in the general level of prices and a fall in the purchasing power of money','Fall in the general level of prices and a rise in the purchasing power of money','Rise in the general level of prices and a fall in the purchasing power of money','Rise in the general level of prices and a rise in the purchasing power of money'],2,
    'Inflation is a rise in prices, which means each unit of money buys less — a fall in purchasing power.'),
  sq(2,'Which of the following is NOT one of the main functions of the Bank of England?',
    ['Adviser to the government','Banker to the government','Issuer of banknotes','Regulator of primary markets'],3,
    'Regulating primary markets is not a Bank of England function — its roles are around banking, note issue, monetary policy and financial stability.'),
  sq(3,'The main stock market index in France is the:',
    ['Dax','Nikkei','CAC 40','NASDAQ'],2,
    'The CAC 40 is France\u2019s leading index (Dax is German, Nikkei is Japanese, NASDAQ is American).'),
  sq(4,'Who issues corporate bonds?',
    ['Primary markets','Investment trusts','Governments','Companies'],3,
    'Corporate bonds are, by definition, issued by companies (government-issued bonds are gilts).'),
  sq(5,'To be automatically classed as a UK resident for tax purposes, an individual needs to be present in the UK for at least:',
    ['365 days in a tax year','183 days in a tax year','30 days in a tax year','90 days in a tax year'],1,
    '183 days or more in a tax year is the automatic UK tax residence threshold.'),
  sq(6,'James left 50% of his IHT nil rate band to his son and the rest of his estate to his wife Julia, who became sole owner of their house. What nil rate band(s) would be available on Julia\u2019s death if she leaves everything to her son?',
    ['200% of the nil rate band and 200% of the residence nil rate band','150% of the nil rate band and 100% of the residence nil rate band','100% of the nil rate band and 200% of the residence nil rate band','150% of the nil rate band and 200% of the residence nil rate band'],3,
    'Julia inherits James\u2019s unused 50% nil rate band (giving her 150% in total) and, since she leaves the home to a direct descendant, both spouses\u2019 residence nil rate bands (200% in total) are available.'),
  sq(7,'Which of the following cannot be deducted from the disposal price of an asset to calculate the CGT gain?',
    ['Buying costs','Maintenance and repair costs','Initial purchase price','Selling costs'],1,
    'Repair and maintenance costs are never an allowable CGT deduction — only acquisition, enhancement and disposal costs qualify.'),
  sq(8,'Which of the following is true regarding the RPI and the CPI?',
    ['Some housing-related costs are included in the CPI but not the RPI','Some housing-related costs are included in the RPI but not the CPI','House prices are included in the CPI but not the RPI','House prices are included in the RPI but not the CPI'],1,
    'The RPI includes certain housing costs (such as mortgage interest payments and council tax) that the CPI does not.'),
  sq(9,'MoneyHelper does not provide advice and guidance on:',
    ['Debt-related matters','Pensions','Investments','Money management'],2,
    'MoneyHelper offers free guidance on debt, pensions and money management, but does not give regulated investment advice.'),
  sq(10,'The Consumer Duty requires firms to adhere to three cross-cutting obligations, which include all of the following EXCEPT:',
    ['To act in good faith','To avoid foreseeable harm to customers','To enable and support retail customers to pursue their financial objectives','The fair treatment of customers'],3,
    '"Fair treatment of customers" (TCF) was the earlier regulatory framework\u2019s language; the Consumer Duty\u2019s three cross-cutting obligations are to act in good faith, avoid foreseeable harm, and support customers in pursuing their financial objectives.'),
  sq(11,'What is the typical deferred period on an accident, sickness and unemployment policy?',
    ['14 days','60 days','30 days','90 days'],1,
    'A typical ASU (accident, sickness and unemployment) policy has a deferred period of around 60 days.'),
  sq(12,'Alan and Clare, each with children from previous relationships, left their own estates to their own children, owning their property as tenants-in-common. On Alan\u2019s death, what happens to the property?',
    ['Alan\u2019s children could force Clare to sell the property to settle their inheritance','Clare would become the legal owner and inherit Alan\u2019s share under the right of survivorship','The children would become joint legal owners with Clare','Clare would become the sole legal owner, holding Alan\u2019s share of the value for his children'],3,
    'Under a tenancy in common, Alan\u2019s equitable share passes per his will (to his children), while Clare — as the surviving joint legal owner — continues to hold legal title, now also holding Alan\u2019s share on trust for his children.'),
  sq(13,'Claudia will receive benefits from her father\u2019s trust only if her brother dies before the age of 25. What type of beneficiary is she?',
    ['Absolute','Bereaved minor','Remainderman','Contingent'],3,
    'Her entitlement depends on a future uncertain event (her brother\u2019s death before 25) — this makes her a contingent beneficiary.'),
  sq(14,'Brian made a will and, three months later, got married. In what circumstances would his will remain valid?',
    ['Only if the will was post-dated','In no circumstances','In all circumstances','Only if the will was written in anticipation of getting married'],3,
    'Marriage automatically revokes an earlier will UNLESS it was made specifically in contemplation of that marriage.'),
  sq(15,'Responsibility for setting the UK Bank Rate lies with:',
    ['The Chancellor of the Exchequer','The Governor of the Bank of England','The Monetary Policy Committee of the Bank of England','HM Treasury'],2,
    'The MPC (not the Governor alone, the Treasury or the Chancellor) is responsible for setting the Bank Rate.'),
  sq(16,'What is one of the main powers granted to the Financial Policy Committee?',
    ['Ensure the relevant markets function well','Intervene in the authorisation of dual-regulated firms','Make recommendations to the PRA and the FCA','Set interest rates to manage the money supply'],2,
    'The FPC identifies systemic risks and can make recommendations and directions to the PRA and FCA; it does not itself set interest rates (that\u2019s the MPC).'),
  sq(17,'Maria complained about her occupational pension scheme, and the trustees initiated the Internal Dispute Resolution Procedure. How long do the trustees have to provide a formal response?',
    ['28 days','8 weeks','4 months','1 month'],2,
    'Under IDRP, trustees generally have up to 4 months to provide a formal response to a complaint.'),
  sq(18,'A specific responsibility of the FCA is to:',
    ['Maintain the stability of the financial system through macro-prudential supervision','Take action to prevent anti-competitive behaviour','Understand the main threats to the stability of the financial system','Oversee the prudential supervision of firms not supervised by the PRA'],3,
    'The FCA prudentially supervises firms that are not dual-regulated by the PRA (solo-regulated firms); macro-prudential stability is a Bank of England/FPC function.'),
  sq(19,'Under its enforcement powers, the FCA can ask the courts to require an individual to forfeit any profit made in contravention of the regulations. This is known as:',
    ['Damages','Redress','Restitution','Restoration'],2,
    'Restitution is the term for a court order requiring wrongly-gained profits (or losses caused) to be repaid.'),
  sq(20,'How many primary strategic objectives does the FCA have?',
    ['One','None','Two','Three'],0,
    'The FCA has one single strategic objective — to ensure relevant markets function well — supported by three operational objectives.'),
  sq(21,'Which body is responsible for the prudential regulation of credit unions?',
    ['The Prudential Regulation Authority','The Bank of England','The Financial Ombudsman Service','The Financial Conduct Authority'],0,
    'Credit unions are prudentially regulated by the PRA.'),
  sq(22,'Which role at an authorised firm is LEAST likely to be subject to the FCA\u2019s conduct rules for individuals?',
    ['Non-executive director','Security officer','Marketing director','Financial adviser'],1,
    'A security officer role is least likely to be caught by the conduct rules, which focus on those with customer-facing, managerial or governance responsibilities.'),
  sq(23,'Which of the following is NOT one of the components of the FCA\u2019s fit and proper test for individuals subject to the Certification Regime?',
    ['Competence and capability','Honesty, integrity and reputation','Financial soundness','Experience and compliance'],3,
    'The fit and proper test covers competence/capability, honesty/integrity/reputation and financial soundness — "experience and compliance" as a combined category is not one of its components.'),
  sq(24,'Harry\u2019s role falls under the Certification Regime. This means:',
    ['He could have oversight of the firm\u2019s compliance function','He must be approved by the FCA','His role would be described as a material risk taker','His fitness for the role would be assessed bi-annually'],2,
    'Certification Regime roles are those capable of significant harm to the firm or its customers — "material risk taker" is a typical example of such a role.'),
  sq(25,'Carlo is being assessed against the \u2018fit and proper\u2019 test. Assessing his credit records is primarily to check his:',
    ['Capability','Competence','Financial soundness','Honesty, integrity and reputation'],2,
    'Credit record checks are used primarily to assess financial soundness.'),
  sq(26,'(Case study: Thomas) At which stage of the financial life cycle is Thomas most likely to be?',
    ['Established family','Student','Young adult in employment','Young family'],2,
    'Thomas has just started his first job after graduating and has no dependants mentioned — this fits "young adult in employment".'),
  sq(27,'What type of finance is Thomas most likely taking out to help with his house purchase?',
    ['A repayment mortgage','A second-charge loan','An interest-only mortgage','An unsecured loan'],0,
    'The scenario states the finance is arranged to be fully repaid by the end of its term — the defining feature of a repayment mortgage.'),
  sq(28,'Which insurance product gives Thomas a regular income in the event of long-term ill health?',
    ['Accident, sickness and unemployment insurance','Critical illness cover','Income protection insurance','Term assurance'],2,
    'Income protection insurance is designed to pay an ongoing replacement income for long-term incapacity, beyond the point where employer sick pay stops.'),
  sq(29,'What is the most suitable deferred period for Thomas\u2019s long-term ill-health cover, given his employer provides 6 months\u2019 sick pay?',
    ['30 days','60 days','13 weeks','26 weeks'],3,
    'To avoid paying for cover that duplicates his 6 months (26 weeks) of employer sick pay, a 26-week deferred period is the most cost-effective match.'),
  sq(30,'Based on Thomas\u2019s £35,000 salary, what maximum monthly ill-health benefit could he typically arrange?',
    ['£1,750.00','£1,895.83','£2,188.00','£2,333.33'],1,
    'Income protection is typically capped at around 65% of gross income: £35,000 × 65% ÷ 12 ≈ £1,895.83 per month.'),
  sq(31,'(Case study: five students buying a flat together) On which basis will their solicitor arrange ownership, given they want a defined equitable share each?',
    ['All will be registered as legal owners', 'Joint tenancy','Single ownership with rental agreements for the remainder','Tenancy in common'],3,
    'Tenancy in common gives each owner a distinct, defined equitable share — exactly what the students want, unlike a joint tenancy where shares are not individually defined.'),
  sq(32,'What is the maximum number of legal owners allowed for a property?',
    ['Two','Four','Six','No limit'],1,
    'UK land law limits the number of registered legal owners of a property to a maximum of four, even though there can be more equitable/beneficial owners.'),
  sq(33,'When registered with the Land Registry, on what basis will the five students\u2019 purchase be registered?',
    ['It does not have to be registered as the flat is leasehold','On a joint tenancy basis','On a multiple tenancy basis','On a tenancy in common basis'],1,
    'Legal title can only be held as a joint tenancy (max 4 legal owners) even where the beneficial interests are held as tenants in common.'),
  sq(34,'If one of the five students dies, what happens to their share?',
    ['The property must be sold and funds split between the four owners and the deceased\u2019s beneficiary equally','The surviving legal owners remain joint legal owners and the deceased\u2019s beneficiary becomes a beneficial owner','The surviving owners must buy the deceased owner\u2019s share from their estate','The surviving owners remain joint equitable owners and the beneficiary also becomes a beneficial owner'],1,
    'Legal title (joint tenancy) passes automatically to the surviving legal owners by survivorship, while the deceased\u2019s equitable (tenancy in common) share passes to their beneficiary.'),
  sq(35,'If the property is sold after their course for a 20% gain, how much profit does each of the five students make?',
    ['£5,600','£9,600','£28,000','£48,000'],1,
    'Total gain = £240,000 × 20% = £48,000, split five ways = £9,600 each.'),
  sq(36,'(Case study: FCA supervisors) Regarding the FCA\u2019s approach to supervision, Alpha Bank plc would be classified as a:',
    ['Fixed portfolio firm','Flexible portfolio firm','Proactive portfolio firm','Reactive portfolio firm'],0,
    'A large firm with a dedicated, ongoing supervisory relationship (like Alpha Bank plc has with Freddie\u2019s team) is a fixed portfolio firm.'),
  sq(37,'The thematic work carried out by Omari is essentially:',
    ['Investigating individual contraventions of regulatory principles and codes of practice','Pre-emptive identification of potential harm through review and assessment of firms','Reviewing previous cases to ensure the correct action has been taken','Wider diagnostic or remedy work where there is actual or potential harm across a few firms'],3,
    'Thematic work looks across multiple firms at a common issue, rather than investigating one firm\u2019s individual breach.'),
  sq(38,'The FCA\u2019s available remedies for a serious contravention do NOT include:',
    ['A custodial sentence of up to 14 years','A statement of misconduct and financial penalty','Variation of the firm\u2019s permissions','Withdrawal of approval for specific individuals'],0,
    'Custodial sentences are a matter for the criminal courts, not a remedy the FCA itself can impose — its own toolkit covers financial penalties, permission variations and approval withdrawal.'),
  sq(39,'A complaint about a product feature that may cause harm to a significant number of consumers is referred to as a:',
    ['Direct complaint','Regulatory impeachment','Superior complaint','Super-complaint'],3,
    'A "super-complaint" is the term for a complaint raised on behalf of a wide group of consumers about a systemic issue.'),
  sq(40,'As far as regulation and supervision is concerned, Alpha Bank plc — a large retail bank — is most likely to be:',
    ['Prudentially regulated by the PRA and for conduct by the FCA','Regulated for conduct and prudential matters by the FCA','Prudentially regulated by the PRA and classed as a P3 firm','Regulated for conduct and prudential matters by the PRA'],0,
    'Large deposit-taking banks are "dual regulated" — prudentially by the PRA, and for conduct by the FCA.')
]
