import type { Question } from './types'

// CeMAP 1's own "Unit 1 – Specimen Paper B", reproduced as an ORIGINAL supplied mock exam.
// Answers verified against CeMAP_1__Delegate_2026.pdf, "ANSWERS" section, "UNIT 1 SPECIMEN PAPER B".

function sq(n: number, text: string, options: string[], correctIndex: number, explanation: string): Question {
  return {
    id: `c1-u1-specB-q${n}`, module: 'cemap1', unitKey: 'unit1', topicKey: 'specimen-b',
    text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: 'CeMAP 1, Unit 1 Specimen Paper B', origin: 'original'
  }
}

export const specimenPaperB: Question[] = [
  sq(1,'Which part of the FCA Handbook covers the Principles for Businesses?',
    ['Business Standards', 'High Level Standards', 'Prudential Standards', 'Training and Competence'],1,
    'The Principles for Businesses sit within the Handbook\u2019s High Level Standards section.'),
  sq(2,'Which types of pension scheme are regulated by The Pensions Regulator?',
    ['Personal pensions only', 'Stakeholder pensions only', 'Work-based schemes only', 'All types of UK pension scheme'],2,
    'The Pensions Regulator\u2019s remit is specifically work-based (occupational) pension schemes.'),
  sq(3,'Where the FCA engages in wider diagnostic remedy work with potential harm across a number of firms, it is exercising its supervision under which heading?',
    ['Reactive', 'Proactive', 'Redemptive', 'Thematic'],3,
    'Thematic work looks across multiple firms at a common issue, rather than one firm\u2019s individual breach.'),
  sq(4,'Who owns mutual organisations?',
    ['Members', 'Shareholders', 'The board of directors', 'The government'],0,
    'Mutuals (like many building societies) are owned by their members, not external shareholders.'),
  sq(5,'The three "cross-cutting" obligations resulting from Principle 12 include all of the following EXCEPT that firms must:',
    ['Act in good faith', 'Avoid foreseeable harm to customers', 'Enable and support customers to pursue their financial objectives', 'Ensure professional clients are treated the same way as retail customers'],3,
    'Treating professional clients the same as retail customers is not one of the three cross-cutting obligations, and would actually contradict the tiered client protection system.'),
  sq(6,'When a public limited company issues shares directly to a shareholder via a rights issue, this is an example of:',
    ['Aggregation', 'Disintermediation', 'Maturity transformation', 'Intermediation'],1,
    'Disintermediation is where funds move directly between parties without going through a financial intermediary — a rights issue is a direct company-to-shareholder transaction.'),
  sq(7,'For a will to be valid in England, what minimum number of witnesses must it have?',
    ['One', 'Two', 'Three', 'Four'],1,
    'A valid English will requires at least two witnesses.'),
  sq(8,'Conduct regulation focuses on the way a financial firm:',
    ['Holds sufficient funds to cover potential losses', 'Manages its financial risks', 'Meets its financial obligations', 'Markets its products and deals with its customers'],3,
    'Conduct regulation (the FCA\u2019s remit) concerns how firms sell to and treat customers, as distinct from prudential regulation.'),
  sq(9,'To which body is the FCA directly accountable?',
    ['HM Treasury', 'The Bank of England', 'The Financial Ombudsman Service', 'The Prudential Regulation Authority'],0,
    'The FCA is accountable to HM Treasury, which has overall responsibility for UK financial services.'),
  sq(10,'Ravi, an IFA authorised to hold client money, wants to \u2018pay away\u2019 dormant cash to a registered charity. What applies?',
    ['Ravi must write or email the client at least twice before the transfer', 'Ravi would need FCA permission to make the transfer', 'There must be at least £500 in the account', 'There must have been no activity for at least 6 years'],3,
    'Money can only be paid away to charity after 6 years of no activity (for money; 12 years for assets).'),
  sq(11,'Which is NOT a requirement for a policy arranged under the Married Women\u2019s Property Act 1882?',
    ['It must be an own-life policy', 'It must be for the benefit of the spouse, child or civil partner of the assured', 'The policy must be taken out in England and Wales', 'The wording must refer to the Act'],3,
    'The law does not require the policy wording to expressly reference the Act, only that it clearly intends to benefit a spouse/children.'),
  sq(12,'Which oversight group is responsible for providing assurance that a firm\u2019s accounts are free from material mis-statement?',
    ['External auditors', 'Internal auditors', 'Compliance officers', 'Trustees'],0,
    'External auditors independently verify that published accounts are free from material mis-statement.'),
  sq(13,'Disposal of which of the following would NOT give rise to a CGT charge?',
    ['A main residence', 'Investment trusts', 'Shares', 'Unit trusts'],0,
    'A main residence benefits from principal private residence relief, exempting it from CGT.'),
  sq(14,'Melanie is subject to the FCA\u2019s Certification Regime at a large authorised firm. What is she MOST likely to be undertaking?',
    ['Chief executive', 'Human resources officer', 'Non-executive director', 'Mortgage adviser'],3,
    'A customer-facing role such as mortgage adviser is a classic Certification Regime role, unlike the other options which are senior management functions.'),
  sq(15,'Which organisation works with the financial services sector and other stakeholders to develop a national strategy to improve financial capability?',
    ['MoneyHelper', 'Bank of England', 'Which?', 'The FCA'],0,
    'MoneyHelper (from the Money and Pensions Service) leads on financial capability strategy.'),
  sq(16,'Which type of investment typically pays regular interest?',
    ['Commercial paper', 'Corporate bonds', 'Equities', 'Treasury bills'],1,
    'Corporate bonds pay a fixed regular coupon (interest); equities pay discretionary dividends, and money market instruments like commercial paper/T-bills are usually issued at a discount rather than paying periodic interest.'),
  sq(17,'The DAX is the main stock market of which country?',
    ['China', 'France', 'Hong Kong', 'Germany'],3,
    'The DAX is Germany\u2019s principal stock market index.'),
  sq(18,'Where a company has defaulted on some or all of its debt obligations, it is most likely to have an S&P Global rating of:',
    ['A', 'B-', 'D', 'C'],2,
    'A "D" rating specifically denotes default under S&P\u2019s rating scale.'),
  sq(19,'Harold pays Class 4 National Insurance. This confirms that he is:',
    ['An employer', 'Employed only', 'Making voluntary contributions', 'Self-employed only'],3,
    'Class 4 NICs are paid by the self-employed on their profits.'),
  sq(20,'The role of the Competition and Markets Authority (CMA) does NOT include which responsibility?',
    ['Ensuring that relevant markets function well', 'Investigating corporate mergers between organisations', 'Protecting consumers from unfair trading practices', 'Taking action to prevent anti-competitive behaviour'],0,
    '"Ensuring relevant markets function well" is the FCA\u2019s strategic objective, not a CMA responsibility.'),
  sq(21,'Which body has an objective of promoting the safety and soundness of the firms it regulates?',
    ['The PRA', 'The FCA', 'The Bank of England', 'The Pensions Regulator'],0,
    'Promoting safety and soundness is one of the PRA\u2019s four statutory objectives.'),
  sq(22,'What is the maximum benefit that generally applies to an individual income protection insurance policy, as a percentage of pre-disability earnings?',
    ['Between 30% and 40%', 'Between 50% and 65%', 'Between 65% and 75%', 'Between 80% and 100%'],1,
    'IPI benefits are typically capped at 50-65% of pre-disability earnings.'),
  sq(23,'Which is most commonly an indicator of an increase in the M4 supply of money?',
    ['Decreasing consumer borrowing', 'Decreasing consumer spending', 'Increased public confidence', 'Increasing rates of inflation'],3,
    'Rapid M4 (broad money) growth is a classic inflation warning sign.'),
  sq(24,'John faced a bankruptcy petition in April 2023, having carried out several \u2018prior transactions\u2019 in previous years. What is the earliest prior transaction the trustee in bankruptcy could consider attacking?',
    ['April 2013', 'April 2016', 'April 2018', 'April 2021'],2,
    'The attack period can extend to 5 years before bankruptcy if the individual was insolvent at the time of the transaction — from an April 2023 petition, that reaches back to April 2018.'),
  sq(25,'The Financial Conduct Authority\u2019s strategic objective is to:',
    ['Ensure that the relevant markets function well', 'Protect and enhance the integrity of the UK financial system', 'Promote effective competition in the interests of consumers', 'Secure an appropriate degree of protection for consumers'],0,
    'Ensuring relevant markets function well is the FCA\u2019s single strategic objective; the other three are operational objectives.'),
  sq(26,'(Case study: Colin and Karen, reviewing retirement plans) Which stage of the financial life cycle are Colin and Karen LEAST likely to be at?',
    ['Established family', 'Mature household', 'Retirement', 'Young adults in employment'],3,
    'Having just repaid their mortgage and actively reviewing retirement plans, they are clearly well past the "young adults" stage.'),
  sq(27,'Karen\u2019s pension benefits from her employer\u2019s defined-benefit scheme will ultimately be based on:',
    ['Her national insurance contribution record', 'Her salary and years\u2019 service', 'The growth of the fund', 'The size of her fund'],1,
    'A defined benefit scheme calculates the pension as a fraction of salary and years of service, not on investment growth or fund size.'),
  sq(28,'What is the earliest age at which Karen can take her pension benefits?',
    ['A date of Karen\u2019s choice', 'The normal minimum pension age', 'The pension scheme\u2019s defined retirement age', 'State pension age'],1,
    'The normal minimum pension age is the earliest age at which pension benefits can generally be accessed.'),
  sq(29,'Should Karen raise a complaint about her occupational pension scheme, to whom should she refer the matter?',
    ['The Financial Ombudsman Service', 'The Pensions Ombudsman', 'The Pensions Regulator', 'The scheme\u2019s trustees'],3,
    'The complaint must first go to the scheme trustees (via the IDRP) before the Pensions Ombudsman becomes involved.'),
  sq(30,'Colin made a voluntary NIC and Karen\u2019s employer paid the appropriate NICs on her behalf. What classes are these respectively?',
    ['Class 1 and 3', 'Class 3 and 1', 'Class 3 and 4', 'Class 4 and 3'],1,
    'Colin\u2019s voluntary contribution is Class 3; Karen\u2019s employer-paid contribution is Class 1.'),
  sq(31,'(Case study: Paul sets up a trust giving Joanna an immediate income for life, with the balance passing to her children Mike and Sarah on her death) Which type of trust is most likely being used?',
    ['A discretionary trust', 'A will trust', 'An absolute trust', 'An interest in possession trust'],3,
    'Joanna receiving income for life as "life tenant", with Mike and Sarah benefiting afterward, is the defining structure of an interest in possession trust.'),
  sq(32,'Who is/are the settlor(s) of the trust?',
    ['Joanna', 'Mike and Sarah', 'Paul', 'The legal adviser'],2,
    'Paul, who creates the trust and transfers the assets into it, is the settlor.'),
  sq(33,'What tax charge, if any, will the trust be subject to when created?',
    ['Joanna will be subject to CGT on the total amount transferred', 'No tax is due as the transfer is a chargeable lifetime transfer', 'Paul may be subject to an IHT charge as it is a chargeable lifetime transfer', 'Paul will be subject to income tax on the transfers'],2,
    'A lifetime gift into an interest in possession trust is a chargeable lifetime transfer, potentially triggering an immediate IHT charge on the excess over the nil rate band.'),
  sq(34,'Who is/are the remaindermen of the trust?',
    ['Joanna', 'Mike and Sarah', 'No one', 'Paul'],1,
    'Mike and Sarah, who benefit after Joanna\u2019s (the life tenant\u2019s) interest ends, are the remaindermen.'),
  sq(35,'Who is/are the beneficiaries of the trust?',
    ['Joanna', 'Joanna, Mike and Sarah', 'Mike and Sarah', 'Paul'],1,
    'Joanna (life tenant) and Mike and Sarah (remaindermen) are all beneficiaries of the trust, just at different points in time.'),
  sq(36,'(Case study: Fairfunds Ltd, a small asset manager with 25 staff) In terms of SM&CR firm classification, Fairfunds Ltd is most likely to be a:',
    ['Core firm', 'Enhanced firm', 'Exempt firm', 'Reserved firm'],0,
    'A small firm of this size, without the scale/complexity warranting Enhanced status, most likely falls into the baseline "Core" category.'),
  sq(37,'For Peter, Jim and Gloria to be approved as senior managers under SM&CR, what must be included in each FCA application?',
    ['A declaration of trust', 'An annual audit of their personal finances', 'An annual test of continued competence', 'A statement of responsibilities'],3,
    'A statement of responsibilities, outlining the areas each senior manager is responsible for, must accompany each application.'),
  sq(38,'Gloria has taken on more than one senior management function. To comply with FCA rules:',
    ['As CEO, Peter is personally responsible for all of Gloria\u2019s regulated activities', 'Gloria needs approval from Peter for each function', 'Gloria needs approval from the FCA for each senior management function', 'Peter can approve Gloria for any function once she is FCA-authorised'],2,
    'Each senior management function an individual holds requires separate FCA approval, to prevent "overloading" of unsupervised responsibility.'),
  sq(39,'Under SM&CR, when fully trained, Jacob will be a(n):',
    ['Appointed representative', 'Approved person', 'Certified person', 'Competent adviser'],2,
    'As a trainee fund manager rising into a role subject to firm-level fitness assessment, Jacob will become a "certified person" under the Certification Regime.'),
  sq(40,'Gloria carried out Jacob\u2019s fitness and propriety test and found he had previously been a director of a company that became insolvent, though he gave an adequate explanation and passed. Which element of the assessment could this have affected?',
    ['Capability', 'Competence', 'Honesty, integrity and reputation', 'Professionalism and respectability'],2,
    'Past involvement in company insolvency is assessed under the "honesty, integrity and reputation" limb of the fit and proper test.')
]
