import type { Question } from './types'

// CeMAP 1's own "Unit 2 – Specimen Paper B", reproduced as an ORIGINAL supplied mock exam.
// Answers verified against CeMAP_1__Delegate_2026.pdf, "ANSWERS" section, "UNIT 2 - SPECIMEN PAPER B".

function sq(n: number, text: string, options: string[], correctIndex: number, explanation: string): Question {
  return {
    id: `c1-u2-specB-q${n}`, module: 'cemap1', unitKey: 'unit2', topicKey: 'specimen-b',
    text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: 'CeMAP 1, Unit 2 Specimen Paper B', origin: 'original'
  }
}

export const unit2SpecimenPaperB: Question[] = [
  sq(1,'Prime responsibility for setting an ethical culture in a firm lies with:',
    ['Departmental management', 'Outside specialists', 'Senior management', 'The FCA'],2,
    'Senior management must lead from the front in establishing and demonstrating a firm\u2019s ethical standards.'),
  sq(2,'Which would be LEAST likely to cause concern about a firm\u2019s ethical standards?',
    ['Focus on competitive pricing', 'Rewards to senior management not justified by performance', 'The quality of products and impact of charges', 'Working with other firms to influence the market'],0,
    'Competitive pricing is a normal, benign business practice, unlike the other options which raise genuine ethical concerns.'),
  sq(3,'Which section of the FCA Handbook covers the client money rules?',
    ['Client Assets Sourcebook', 'Dispute Resolution', 'High Level Standards', 'Prudential Standards'],0,
    'Client money rules are set out in the Client Assets Sourcebook (CASS).'),
  sq(4,'The fair treatment of customers is an integral part of the FCA\u2019s:',
    ['General Provisions', 'Principles for Businesses', 'Prudential Sourcebook', 'Training and Competence Sourcebook'],1,
    'Fair treatment of customers is embedded within the Principles for Businesses.'),
  sq(5,'How much does the Financial Ombudsman Service charge consumers for investigating their claim?',
    ['Nil', '£10', '£50', '£100'],0,
    'The FOS is free of charge to consumers, funded instead by a levy on authorised firms.'),
  sq(6,'Which FCA Principle for Businesses covers the Consumer Duty?',
    ['Principle 7', 'Principle 8', 'Principle 9', 'Principle 12'],3,
    'The Consumer Duty is Principle 12 — "a firm must act to deliver good outcomes for retail customers".'),
  sq(7,'The FCA\u2019s regulatory regime is primarily based on:',
    ['Inspection, regulation and reporting', 'Mandatory reporting principles and regulations', 'The Principles for Businesses', 'The fair treatment of customers'],2,
    'The Principles for Businesses form the foundation of the FCA\u2019s principles-based regulatory approach.'),
  sq(8,'Which would NOT normally be classed as a stakeholder in an authorised firm?',
    ['A competitor firm', 'A customer', 'A shareholder', 'An employee'],0,
    'A competitor is not typically considered a stakeholder — stakeholders include shareholders, customers, employees, suppliers, the community and the environment.'),
  sq(9,'What is the latest point in the sales process that a key features document for a personal pension should be given?',
    ['At the outset of the meeting', 'Before a recommendation is made', 'Before the sale is concluded', 'When the cancellation notice is sent'],2,
    'Key features documentation must be provided before the sale is concluded.'),
  sq(10,'Which new product sale requires a suitability report?',
    ['An investment of £1,000 into a unit trust', 'An investment of £2,000 into a cash ISA', 'Arranging a £100,000 repayment mortgage', 'Arranging a £200,000 interest-only mortgage'],0,
    'Unit trust investments require a suitability report — mortgages and cash ISAs do not fall within the specific suitability report product list.'),
  sq(11,'Consequentialist ethics asserts that an action is right if it:',
    ['Follows a firm\u2019s corporate social responsibility policy', 'Follows a moral rule or principle', 'Represents what a virtuous person would do', 'Results in the best outcome'],3,
    'Consequentialist ethics judges an action by its outcome — "the ends justify the means".'),
  sq(12,'Where identification has not previously been obtained, a bank must carry out an identity check if a transaction exceeds:',
    ['€2,000', '€5,000', '€10,000', '€15,000'],3,
    'The standard AML identity check threshold for an occasional transaction is €15,000.'),
  sq(13,'Which type of ethical theory is the main focus of business ethics?',
    ['Applied ethics', 'Meta-ethics', 'Natural ethics', 'Normative ethics'],0,
    'Applied ethics — applying ethical principles to real-world situations — is the practical focus of business ethics.'),
  sq(14,'What is the maximum claim amount for investment business that an individual could successfully make under the FSCS?',
    ['£50,000', '£85,000', '£100,000', '£170,000'],1,
    'Investment business claims are protected up to 100% of the first £85,000.'),
  sq(15,'Which FCA customer category would typically apply to an investment firm for the straightforward execution of transactions?',
    ['Eligible counterparty', 'Private client', 'Professional client', 'Retail client'],0,
    'An eligible counterparty typically receives limited, execution-only-type services.'),
  sq(16,'The FOS found in a client\u2019s favour against an authorised firm. The ruling is binding on:',
    ['Both the firm and the client', 'Neither the firm nor the client', 'The client only', 'The firm only'],3,
    'FOS decisions bind the firm, but not the complainant, who retains the right to pursue the matter in court instead.'),
  sq(17,'Which type of advice provides personal recommendations relating to a specific need, at the client\u2019s request?',
    ['All types of streamlined advice', 'Focused advice', 'Guidance', 'Restricted advice'],1,
    'This describes focused advice — a personal recommendation limited to a specific stated need.'),
  sq(18,'Harvey received advice 10 years ago and realised 5 years ago he might have been badly advised. Within what maximum further period must he complain?',
    ['He is unable to complain as he is already out of time', 'One year', 'Two years', 'Three years'],0,
    'The FOS time limit (6 years from event or 3 years from awareness, whichever is later) has already passed for Harvey.'),
  sq(19,'A question asking "what would happen if..." is which type of question?',
    ['A closed question', 'A probing question', 'An open question', 'Factfinding'],2,
    'This is an open-ended, hypothetical-style question designed to explore feelings and attitudes.'),
  sq(20,'In what circumstances is an independent financial adviser permitted to use a panel of providers?',
    ['In all circumstances', 'In no circumstances', 'Only if approved by the FCA', 'Only if the panel is sufficiently broad in composition'],3,
    'A panel is only compatible with independence if it is sufficiently broad and diverse, and regularly reviewed.'),
  sq(21,'Christian, Katherine and Emma are ordinary partners; Greg, Donna and Andy own their business through an LLP. Which is true?',
    ['A partnership must have at least three partners', 'Christian, Katherine and Emma\u2019s partnership is a legal entity in its own right', 'Greg, Donna and Andy will be able to keep simpler accounts', 'Only Christian, Katherine and Emma are personally liable for their business\u2019s debts'],3,
    'Ordinary partners are personally liable for partnership debts; LLP partners are not — this is the fundamental distinction between the two structures.'),
  sq(22,'For what minimum period must a firm retain sales records, including suitability, for life policies and investment-based policies?',
    ['Three years', 'Five years', 'Seven years', 'Indefinitely'],1,
    'Records relating to life policies and investment bonds must be kept for 5 years.'),
  sq(23,'Harry\u2019s role falls under the Certification Regime. This means:',
    ['He could have oversight of the firm\u2019s compliance function', 'He must be approved by the FCA', 'His fitness for the role must be assessed bi-annually', 'His role would be described as a material risk taker'],3,
    'A typical Certification Regime role is a "material risk taker" — a significant harm function certified by the firm, not directly approved by the FCA.'),
  sq(24,'For what minimum period must a firm keep records of a complaint about a stand-alone critical illness policy?',
    ['Three years', 'Five years', 'Six years', 'Seven years'],0,
    'General complaint records must be kept for at least 3 years.'),
  sq(25,'What is the cooling-off period for a stocks and shares ISA?',
    ['7 days', '14 days', '28 days', '30 days'],1,
    'Investment products including stocks and shares ISAs carry a 14-day cooling-off period.'),
  sq(26,'(Case study: Daniel, restricted adviser, close to missing his bonus target) Daniel advises Ruth on income protection with two premium levels (stress included or not). If stress cover means missing the underwriting deadline for his bonus, how should he act?',
    ['Explain the levels but encourage the lower level as quicker cover benefits her too', 'Explain the two levels of cover and the associated underwriting issues', 'Include stress cover as this results in a higher bonus', 'Just discuss the lower level, reviewing it later'],1,
    'Daniel must give Ruth full, unbiased information about both options and let her make an informed decision, regardless of his own bonus incentive.'),
  sq(27,'What should Daniel do regarding the couple\u2019s wills, made before their civil partnership and not updated since?',
    ['Ask for a copy to confirm they were made correctly', 'Confirm that as civil partners the assets automatically pass to the survivor', 'Make no comment, as it is outside his advice range', 'Suggest they consider legal advice regarding the suitability of their existing wills'],3,
    'While drafting wills is outside Daniel\u2019s remit, flagging the need for legal advice given their changed circumstances is an appropriate and responsible step.'),
  sq(28,'Daniel is concerned that colleague Keith\u2019s financial problems are affecting his advice to clients. What is the most appropriate first action?',
    ['Do nothing, as it is not his concern', 'Express concerns to Keith and suggest he talk to their manager', 'Report his concerns to the firm\u2019s compliance officer', 'Report his concerns to their direct manager'],2,
    'Concerns about a colleague\u2019s conduct affecting client outcomes should be reported through compliance channels.'),
  sq(29,'What does Daniel require to prove he is a qualified and competent adviser? 1. Level 3 RQF qualification, 2. Level 4 RQF qualification, 3. SPS every 12 months, 4. SPS every 2 years.',
    ['1 and 3', '1 and 4', '2 and 3', '2 and 4'],0,
    'As a restricted adviser on packaged products (not full investment advice), a Level 3 qualification plus an annual SPS applies.'),
  sq(30,'In providing restricted advice, Daniel is required under FCA rules to:',
    ['Ensure he assesses products from the whole marketplace', 'Ensure he assesses a sufficient range of relevant products in the market', 'Provide advice based on products from one company or a limited number only', 'Provide product and generic information only'],2,
    'Restricted advice is, by definition, based on a limited range of providers/products — not the whole market.'),
  sq(31,'(Case study: Siobhan advising high-net-worth clients Joan and Alistair) What is the maximum age a person can contribute to a personal pension?',
    ['Below 65', 'Below 67', 'Below 70', 'Below 75'],3,
    'Personal pension tax relief is available to UK residents under 75.'),
  sq(32,'Which is true regarding Siobhan\u2019s remuneration for advice given?',
    ['She can only receive commission', 'She can decide whether to operate solely by commission or offer a fee basis', 'She can only receive remuneration by fees', 'She can receive commission on some products but must offer fees in other areas'],1,
    'Advisers giving investment advice must generally be fee-based (commission remains permitted for pure protection sales), but Siobhan has discretion over her overall charging structure within these rules.'),
  sq(33,'As an experienced, competent adviser, Siobhan is required to:',
    ['Complete 21 hours of structured CPD every year', 'Obtain an annual SPS from the FCA', 'Provide evidence of compliance with the regulator\u2019s code of ethics', 'Re-take professional qualifications every 5 years'],0,
    'A minimum of 21 hours of STRUCTURED CPD (within a 35-hour total) is required annually — and the SPS comes from an accredited body, not the FCA directly.'),
  sq(34,'Which is true?',
    ['A suitability report for an IIP trust must always explain why a bare trust was not recommended', 'The cancellation period for a life assurance investment bond in a trust arrangement is 30 days', 'The main difference between IIP trusts and bare trusts is the investment vehicle used', 'Transfers into interest in possession trusts are not considered chargeable lifetime transfers'],3,
    'In the specific circumstances covered here, transfers into this type of interest in possession trust structure are not treated as chargeable lifetime transfers.'),
  sq(35,'Joan and Alistair want investments held within ethical funds only. Which firms are LEAST likely to feature in such funds?',
    ['Firms that pay employees a fair wage', 'Firms that provide secure employment', 'Firms that resort to greenwashing', 'Firms that address environmental issues'],2,
    'Greenwashing firms — falsely claiming environmental credentials — are precisely what ethical fund screening aims to exclude.'),
  sq(36,'(Case study: Mandy and trainee Abdul) Sara asks whether Mandy offers independent or restricted advice, having heard independent advisers: 1. Charge more but offer better service, 2. Must offer all products from all providers, 3. Offer a wider choice than restricted advisers, 4. Can offer independent advice in some areas and restricted in others. Which statements are true?',
    ['1, 3 and 4', '2 and 3', '2, 3 and 4', '3 and 4'],3,
    'Independent advisers do offer a wider product choice (statement 3) and can indeed offer independent advice in some areas while being restricted in others (statement 4) — but they don\u2019t have to offer literally every product from every provider (statement 2 is false), and cost/quality claims (statement 1) aren\u2019t guaranteed.'),
  sq(37,'Mandy, Abdul and next client Piers continue discussing Sara (a mutual acquaintance) after her meeting ends. Which FCA Principles should Mandy and Abdul be mindful of regarding their duties to Sara?',
    ['Integrity (1) and Conflicts of interest (8)', 'Skill, care and diligence (2) and Clients\u2019 assets (10)', 'Market conduct (5) and Consumer duty (12)', 'Customers\u2019 interests (6) and Relationships of trust (9)'],0,
    'Discussing a client\u2019s affairs with a third party raises confidentiality (integrity) concerns and a conflict of interest given the personal connection.'),
  sq(38,'Mandy proceeds to just arrange ISA investments for Graham, who declined a full review. What type of advice will he have received?',
    ['Basic advice', 'Focused advice', 'Guidance', 'Simplified advice'],1,
    'A personal recommendation limited to a specific stated need (ISA investment only) at the client\u2019s request is focused advice.'),
  sq(39,'How should Mandy categorise Sara, Piers and Graham for client protection purposes?',
    ['All three are retail clients, though Graham can elect professional client status', 'All three are retail clients, though Sara and Piers may be classed as potentially vulnerable', 'Sara and Piers are retail clients and Graham is a professional client', 'Sara is a vulnerable retail client; Piers and Graham are professional clients'],1,
    'All three remain retail clients given their circumstances — Sara (recent divorce) and Piers (sudden large inheritance) show characteristics of potential vulnerability given recent life events.'),
  sq(40,'Graham disagrees with Mandy\u2019s ISA recommendation and asks her to invest in different funds of his own choosing. Mandy should:',
    ['Explain she cannot do as he requests', 'Refer him to another adviser for a second opinion', 'Treat him as an execution-only client', 'Treat him as an insistent client'],3,
    'A client who has received advice but chooses to proceed against it is treated as an "insistent client", requiring a signed disclaimer confirming they are acting against advice.')
]
