import type { Question } from './types'

// CeMAP 1's own "Unit 1 – Specimen Paper C", reproduced as an ORIGINAL supplied mock exam.
// Answers verified against CeMAP_1__Delegate_2026.pdf, "ANSWERS" section, "UNIT 1 - SPECIMEN PAPER C".

function sq(n: number, text: string, options: string[], correctIndex: number, explanation: string): Question {
  return {
    id: `c1-u1-specC-q${n}`, module: 'cemap1', unitKey: 'unit1', topicKey: 'specimen-c',
    text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: 'CeMAP 1, Unit 1 Specimen Paper C', origin: 'original'
  }
}

export const specimenPaperC: Question[] = [
  sq(1,'What is the process where lenders and borrowers interact directly rather than through an intermediary?',
    ['Disintermediation', 'Netting', 'Reinsurance', 'Hedging'],0,
    'Disintermediation describes lenders and borrowers dealing directly, bypassing a financial intermediary.'),
  sq(2,'Which is true of supply and demand in oil markets?',
    ['Equilibrium is the term used when supply and demand are balanced', 'Oil producers can increase the market price by increasing production', 'Prices fall when demand exceeds supply', 'Supply and demand have no impact on prices'],0,
    'Equilibrium is the standard economic term for the point where supply and demand are balanced.'),
  sq(3,'Which is FALSE in relation to cash? It is suitable for those who:',
    ['Have short-term saving needs', 'Are needing to establish an emergency fund', 'Require income without taking investment risks', 'Require long-term capital growth'],3,
    'Cash is not suited to long-term capital growth needs — inflation erodes its real value over time, and it lacks the growth potential of other asset classes.'),
  sq(4,'Which is NOT a money market instrument?',
    ['Certificates of deposit', 'Commercial paper', 'Government bonds (gilts)', 'Treasury bills'],2,
    'Gilts are longer-term capital market instruments, not money market instruments (which are short-term, up to 12 months).'),
  sq(5,'Which is NOT an economic objective of a modern government?',
    ['A balance of payments surplus', 'Economic growth', 'Low unemployment', 'Price stability'],0,
    'Balance of payments EQUILIBRIUM (not necessarily a surplus) is the typical objective — a surplus specifically is not the standard goal.'),
  sq(6,'Authorities in one country allow UK firms limited market access, providing regulatory standards are broadly compatible. This describes:',
    ['Equality', 'Equivalence', 'Parity', 'Passporting'],1,
    'This is the definition of "equivalence" — a post-Brexit mechanism distinct from the former EU passporting regime.'),
  sq(7,'Any unused inheritance tax annual gift exemption:',
    ['Cannot be carried forward', 'Can be carried forward for the following tax year but no further', 'Can be carried forward to any of the following three tax years', 'Can be carried forward indefinitely'],1,
    'The annual IHT gift exemption can only be carried forward one tax year if unused.'),
  sq(8,'Which is NOT a role of the Bank of England?',
    ['Banker to the banks', 'Controller of exchange rates', 'Issuer of bank notes', 'Lender of last resort'],1,
    'The Bank of England does not directly control exchange rates as one of its core functions.'),
  sq(9,'A major factor in consumers\u2019 attitudes towards the financial services sector is their:',
    ['High level of satisfaction with their own finances', 'Impression that products are too simplistic', 'Lack of understanding of regulation', 'Limited financial competence'],3,
    'Consumers\u2019 limited financial competence is identified as a key driver of attitudes/engagement with financial services.'),
  sq(10,'Which is NOT a typical need of a sole trader?',
    ['Business banking', 'Business protection', 'Mortgages and loans', 'Shareholder protection'],3,
    'Shareholder protection is relevant to limited companies, not sole traders, who have no shareholders.'),
  sq(11,'An applicant deliberately failed to answer an insurer\u2019s questions fully and accurately on a life proposal form. Under the Consumer Insurance Disclosure Act 2012, what is the MOST severe action the insurer can take on a claim?',
    ['Deduct underpaid premiums from any claim', 'Pay a proportion of the claim related to actual premiums paid', 'Recalculate and backdate the premium based on correct information', 'Reject the claim and keep the premiums paid'],3,
    'A deliberate (reckless) misrepresentation allows the insurer to reject the claim entirely and keep the premiums, the most severe available action.'),
  sq(12,'Roger left his estate under trust for partner Jeremy to benefit as life tenant; on Jeremy\u2019s death, proceeds pass to Roger\u2019s son. What type of trust is this?',
    ['A discretionary trust', 'A flexible trust', 'An absolute trust', 'An interest in possession trust'],3,
    'A named life tenant (Jeremy) with a defined remainderman (Roger\u2019s son) is the structure of an interest in possession trust.'),
  sq(13,'Gerd has set up a trust from which he could potentially benefit. Which tax, normally avoided by placing assets in trust, would still apply?',
    ['Capital gains tax', 'Corporation tax', 'Inheritance tax', 'Withholding tax'],2,
    'A "settlor-interested" trust (where the settlor can still benefit) means the assets remain within the settlor\u2019s estate for IHT purposes.'),
  sq(14,'Which is NOT exempt from authorisation under the Financial Services and Markets Act 2000?',
    ['An independent financial advisory firm', 'Trustees', 'The Bank of England', 'The London Stock Exchange'],0,
    'An IFA firm carrying out regulated activities requires full authorisation, unlike the specifically exempted categories.'),
  sq(15,'Which is NOT an operational objective of the FCA?',
    ['Promote effective competition in the interests of consumers', 'Protect and enhance the integrity of the UK financial system', 'Protect consumers from bad conduct', 'Reduce investment risk for customers'],3,
    'Reducing investment risk for customers is not one of the FCA\u2019s three operational objectives — the FCA doesn\u2019t guarantee investment outcomes.'),
  sq(16,'Which legislation established the PRA and FCA as part of a new regulatory framework?',
    ['The Bank of England and Financial Services Act 2016', 'The Financial Services Act 1986', 'The Financial Services Act 2012', 'The Financial Services and Markets Act 2000'],2,
    'The Financial Services Act 2012 introduced the "twin peaks" PRA/FCA model from April 2013.'),
  sq(17,'Which body\u2019s main responsibility is "identification of, monitoring of, and taking of action to remove or reduce, systemic risks... to protect and enhance the resilience of the UK financial system"?',
    ['HM Treasury', 'The Bank of England', 'The Financial Policy Committee', 'The Prudential Regulation Authority'],2,
    'This is the specific remit of the Financial Policy Committee.'),
  sq(18,'How many objectives does the PRA have?',
    ['One', 'Two', 'Three', 'Four'],3,
    'The PRA has four statutory objectives.'),
  sq(19,'Which organisation uses a Proactive Intervention Framework (PIF)?',
    ['The Bank of England', 'The FCA', 'The FOS', 'The PRA'],3,
    'The PRA uses the PIF for early identification of risks to a firm\u2019s viability.'),
  sq(20,'Which body has the objective of securing an appropriate degree of protection for insurance policyholders?',
    ['The Bank of England', 'The FCA', 'The Pensions Regulator', 'The PRA'],3,
    'This is one of the PRA\u2019s four statutory objectives.'),
  sq(21,'Gary, a senior manager under investigation, faces which FALSE statement?',
    ['Gary must prove that he took reasonable steps to prevent the breach', 'The regulator must prove Gary was a senior manager at the time of the breach', 'The regulator must prove Gary was responsible for the relevant department', 'The regulator must prove the bank breached the regulations'],0,
    'It is the REGULATOR that must prove all elements, including that reasonable steps were not taken — the burden is not on Gary himself.'),
  sq(22,'Which part of the FCA Handbook contains the Principles of Business?',
    ['Business standards', 'High level standards', 'Prudential standards', 'Specialist standards'],1,
    'The Principles for Businesses sit within High Level Standards.'),
  sq(23,'David performs a significant harm function. With what minimum frequency must his fitness and propriety be assessed?',
    ['Monthly', 'Every three months', 'Every six months', 'Annually'],3,
    'Certification Regime assessments must be repeated at least annually.'),
  sq(24,'Which part of the FCA Handbook covers senior management arrangements, systems and controls?',
    ['High level standards', 'Prudential standards', 'Business standards', 'Training and competence'],0,
    'Systems and controls sit within the High Level Standards section, alongside the Principles for Businesses.'),
  sq(25,'The consumer outcomes expected under the Consumer Duty relate to: 1. Products and services 2. Price and value 3. Consumer understanding 4. Consumer support. Which combination is correct?',
    ['1, 2 and 3', '1, 2, 3 and 4', '1, 3 and 4', '2, 3 and 4'],1,
    'All four listed items — products/services, price/value, consumer understanding, and consumer support — are the Consumer Duty\u2019s four outcomes.'),
  sq(26,'(Case study: Alessia, 25, and fianc\u00e9 David, exchanged contracts on a repayment mortgage, want life cover) What is the most suitable life policy for their mortgage concern?',
    ['A single life level term policy on each of them', 'A form of decreasing insurance on a joint life first death basis', 'Level term insurance on a joint life first death basis', 'Whole of life assurance on a joint life second death basis'],1,
    'Decreasing term assurance on a joint-life-first-death basis matches a repayment mortgage\u2019s falling balance at the lowest cost.'),
  sq(27,'What is the most suitable product for Alessia\u2019s £10,000 emergency fund (no risk, may not be best placed currently)?',
    ['Public limited company shares', 'A venture capital trust', 'An instant access cash ISA', 'A fixed rate building society deposit account'],2,
    'An instant access cash ISA provides no-risk, tax-free, readily accessible funds ideal for emergencies.'),
  sq(28,'Given Alessia\u2019s cautious-to-balanced risk attitude, which would be LEAST suitable equity-based investment for her £50,000 growth need?',
    ['Enterprise investment scheme', 'Investment trust', 'Open ended investment company', 'Unit trust'],0,
    'An EIS is a high-risk, unlisted-company investment, unsuitable for a cautious-to-balanced investor compared with diversified collective options.'),
  sq(29,'Alessia asks Mary about the cancellation price on unit trusts. Mary correctly explains it is the price Alessia:',
    ['Would pay to buy units from the manager', 'Is likely to receive if the manager had to buy units back during a dramatic market fall', 'Would receive if she sold units back to the manager', 'Is likely to receive if she cancelled within the cooling-off period'],1,
    'The cancellation price is a rarely-used, lower price applied when the manager must buy back units but has little prospect of reselling them quickly, typically in a falling market.'),
  sq(30,'Which investment products can benefit from "gearing"?',
    ['Cash ISAs', 'Investment trusts', 'OEICs', 'Unit trusts'],1,
    'Investment trusts, as close-ended companies, are uniquely able to borrow (gear) to enhance returns.'),
  sq(31,'(Case study: Paul died leaving a will splitting his estate between children Michael, Keith and Marianne; Marianne is executor) When can Marianne begin distributing the estate?',
    ['Immediately after his death', 'Once letters of administration have been granted', 'Once probate has been granted', 'Once the beneficiaries agree the terms of the will'],2,
    'An executor generally cannot distribute the estate until the Grant of Probate has been obtained.'),
  sq(32,'An additional signed page attached to Paul\u2019s will leaves £10,000 in trust to his grandchild. Which is FALSE about this additional sheet?',
    ['As long as requirements are met, it forms part of the original will', 'It confirms the continuing validity of the original will', 'It forms a codicil to the will', 'Paul\u2019s signature must have been witnessed by at least one person'],3,
    'A codicil, like a will itself, must be witnessed by at least TWO people, not just one — making this statement false.'),
  sq(33,'Michael suggests the children each give up some inheritance to provide for Paul\u2019s partner Diane, effective for IHT purposes, but Keith disagrees. Which is TRUE?',
    ['Keith\u2019s objection would not prevent Michael and Marianne doing as Michael suggests', 'The arrangement must be executed within one year of death for IHT planning', 'The plan cannot go ahead because Keith does not agree', 'The plan can only be achieved through a disclaimer'],0,
    'A Deed of Variation only needs agreement from beneficiaries who are adversely affected by the specific change — Michael and Marianne can vary their own shares without Keith\u2019s consent.'),
  sq(34,'What arrangement is most likely in place to meet the partnership agreement\u2019s requirement on Paul\u2019s death?',
    ['John and George would use personal funds', 'John and George would each have taken life insurance on Paul', 'Paul would have taken life assurance in trust for John and George', 'The agreement permits John and George to use partnership funds'],3,
    'A common structure is for the partnership agreement to allow surviving partners to use partnership funds (often backed by partnership protection insurance) to buy out the deceased\u2019s share.'),
  sq(35,'What is the difference between Paul\u2019s ordinary partnership and a limited liability partnership?',
    ['Only Paul\u2019s partnership requires a partnership agreement', 'The extent of the partners\u2019 responsibility for partnership debts', 'The minimum number of partners required', 'The taxation treatment of profits'],1,
    'The key distinction is liability: ordinary partners are personally liable for partnership debts, while LLP partners have limited liability.'),
  sq(36,'(Case study: Brading Finance, a small sole trader-owned advice firm) In relation to prudential regulation, the FCA would regard Brading Finance as being in which category?',
    ['P1', 'P2', 'P3', 'The FCA would not have prudential responsibility for Brading Finance'],2,
    'A small firm like this, with limited client asset exposure, is likely to be categorised P3 — "prudentially non-significant".'),
  sq(37,'Who at Brading Finance would be subject to the FCA Certification Regime?',
    ['Toby only', 'The three advisers only', 'Toby and the three advisers only', 'Toby, the three advisers and the administrator'],2,
    'Toby (as SMF29/compliance oversight) and the three advisers (customer-facing, significant-harm roles) fall under certification; the administrator\u2019s ancillary role does not.'),
  sq(38,'What senior management function(s) must Brading Finance appoint someone to?',
    ['Limited scope function (SMF 29) only', 'Compliance Oversight function (SMF 16) only', 'Limited scope (SMF 29) and Compliance oversight (SMF 16)', 'Brading Finance would not fall under the Senior Managers Regime'],2,
    'As a sole trader firm with employees (and, given its size/turnover, meeting the compliance oversight threshold), both SMF 29 and SMF 16 are required.'),
  sq(39,'The directory of certified and assessed persons maintained by the FCA is called the:',
    ['Certification Directory', 'Approved Persons Register', 'Financial Services Register', 'Authorisation Register'],2,
    'The Financial Services Register is the FCA\u2019s public directory of certified and approved individuals and firms.'),
  sq(40,'The administrator suggests giving £120 of unclaimed client money (dormant 8 years) to charity since two letters have already been sent. What is the position?',
    ['The firm must hold the money until the client makes contact', 'The firm must contact the client once more before giving the money to charity', 'The firm must contact the client 3 more times before giving it to charity', 'The amount is too high to give to charity without permission'],1,
    'Firms must make reasonable attempts (typically three) to contact the client before paying away — having sent two, one further attempt is needed.')
]
