import type { Question } from './types'

// CeMAP 1's own "Unit 2 – Specimen Paper A", reproduced as an ORIGINAL supplied mock exam.
// Answers verified against CeMAP_1__Delegate_2026.pdf, "ANSWERS" section, "UNIT 2 - SPECIMEN PAPER A".

function sq(n: number, text: string, options: string[], correctIndex: number, explanation: string): Question {
  return {
    id: `c1-u2-specA-q${n}`, module: 'cemap1', unitKey: 'unit2', topicKey: 'specimen-a',
    text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: 'CeMAP 1, Unit 2 Specimen Paper A', origin: 'original'
  }
}

export const unit2SpecimenPaperA: Question[] = [
  sq(1,'Which types of financial advice are types of streamlined advice?',
    ['All regulated advice', 'Focused advice and simplified advice', 'Focused advice only', 'Guidance'],1,
    'Streamlined advice specifically refers to focused advice and simplified advice.'),
  sq(2,'A customer bought 5,000 units at an offer price of £1.00. Seven days later he cancels; the bid price is 85p, offer 90p, cancellation price 83p. How much would he receive back?',
    ['£4,150', '£4,250', '£4,500', '£5,000'],2,
    'Since the value has fallen and this is explained in the contract, he receives the current offer price × units: 90p × 5,000 = £4,500.'),
  sq(3,'An appropriateness test must be undertaken on an execution-only sale of which product?',
    ['Endowment plans used to repay a mortgage', 'OEICs', 'Tax-exempt unauthorised unit trust', 'Unit-linked investment bonds'],2,
    'A tax-exempt unauthorised unit trust is one of the specifically complex products requiring an appropriateness test.'),
  sq(4,'Which is NOT one of the principal money laundering offences?',
    ['Acquiring', 'Concealing', 'Arranging', 'Tipping off'],3,
    'The three principal offences are concealing, arranging and acquiring/using criminal property — tipping off is a separate, related offence.'),
  sq(5,'In what circumstances is an independent financial adviser permitted to use a panel of providers?',
    ['In all circumstances', 'In no circumstances', 'Only if the panel has been approved by the FCA', 'Only if the panel is reviewed regularly'],3,
    'A panel is permitted for independent advice only if it is sufficiently broad/diverse and reviewed regularly, with the ability to go outside it if needed.'),
  sq(6,'Which is true of an adviser\u2019s Statement of Professional Standing (SPS)?',
    ['It can be validated by the adviser\u2019s own firm', 'It is issued by the FCA', 'It is valid for 12 months', 'It must be shown to clients on first contact'],2,
    'An SPS is valid for 12 months, issued by an accredited body (not the FCA or the adviser\u2019s own firm), and does not need to be shown to clients.'),
  sq(7,'Under anti-money-laundering legislation, records of identification obtained from individuals must be held for a minimum of:',
    ['Three years from the beginning of a customer relationship', 'Three years from the end of a customer relationship', 'Five years from the beginning of a customer relationship', 'Five years from the end of a customer relationship'],3,
    'ID evidence must be retained for at least 5 years after the relationship with the customer has ended.'),
  sq(8,'Who is responsible for verifying that a financial adviser at a large firm has completed the required CPD hours each year?',
    ['An accredited body', 'An authorised independent assessor', 'The adviser\u2019s employer', 'The Financial Conduct Authority'],0,
    'The accredited body issuing the adviser\u2019s SPS verifies their annual CPD completion.'),
  sq(9,'Which is NOT a common characteristic of ethical behaviour in business?',
    ['Acting within the rules but not the spirit of the law and regulations', 'Service excellence', 'Social consciousness', 'Transparency'],0,
    'Acting only within the letter (not the spirit) of the law is the opposite of genuine ethical behaviour.'),
  sq(10,'Which of the FCA\u2019s Principles for Businesses covers conflicts of interest?',
    ['Principle 6', 'Principle 7', 'Principle 8', 'Principle 9'],2,
    'Conflicts of interest are covered by Principle 8.'),
  sq(11,'What is the cooling-off period for a cash ISA?',
    ['7 days', '14 days', '28 days', '30 days'],1,
    'Investment products including cash ISAs carry a 14-day cooling-off period.'),
  sq(12,'Under FCA rules, which customer category is afforded the highest level of protection?',
    ['Eligible counterparty', 'Professional client', 'Private client', 'Retail client'],3,
    'Retail clients, generally with the least financial knowledge, receive the highest level of protection.'),
  sq(13,'The requirement for authorised firms to explicitly treat customers fairly is embedded within the:',
    ['Competition and Markets Authority\u2019s rules', 'FCA\u2019s intensive supervision initiative', 'FCA\u2019s Market Conduct sourcebook', 'FCA\u2019s Principles for Businesses'],3,
    'Treating customers fairly (now largely folded into the Consumer Duty) is embedded within the FCA\u2019s Principles for Businesses.'),
  sq(14,'A mortgage adviser is required to pass an appropriate:',
    ['Level 3 qualification within 36 months of taking up the role', 'Level 3 qualification within 48 months of taking up the role', 'Level 4 qualification within 36 months of taking up the role', 'Level 4 qualification within 48 months of taking up the role'],1,
    'Mortgage advisers must pass a Level 3 qualification (e.g. CeMAP) within 48 months of starting to advise under supervision.'),
  sq(15,'Robert received investment advice 7 years ago and realised 3 years ago he might have been badly advised. Within what maximum further period must he complain?',
    ['He is unable to complain as he is already out of time', 'One year', 'Two years', 'Three years'],0,
    'The FOS time limit is 6 years from the event or 3 years from awareness, whichever is later — having realised 3 years ago, Robert has already reached that outer limit.'),
  sq(16,'Where an authorised firm provides a recommendation, the FCA requires that it must be:',
    ['Balanced', 'Fair', 'Relevant', 'Suitable'],3,
    'Suitability is the fundamental FCA requirement for any personal recommendation.'),
  sq(17,'What is the maximum claim amount for long-term care insurance that a married couple could successfully make under the FSCS?',
    ['£85,000', '£100,000', '£175,000', 'Unlimited'],3,
    'Long-term care insurance receives 100% FSCS protection with no upper limit.'),
  sq(18,'For what minimum period must an authorised firm keep records of a complaint about an income protection insurance policy?',
    ['Three years', 'Five years', 'Six years', 'Seven years'],0,
    'Complaint records must generally be kept for at least 3 years.'),
  sq(19,'Which individual conduct rule applies ONLY to senior managers?',
    ['Act with due skill, care and diligence', 'Act with integrity', 'Be open and cooperative with the FCA, PRA and other regulators', 'Disclose any information the FCA or PRA would reasonably expect notice of'],3,
    'This is SM4, one of the senior manager-specific conduct rules, unlike the Tier 1 rules that apply to all covered staff.'),
  sq(20,'Where a firm offers independent financial advice, it is NOT an FCA requirement that the advice is:',
    ['Comprehensive', 'Fair', 'Restricted', 'Unbiased'],2,
    'Independent advice must specifically NOT be restricted — restricted advice is the opposite category.'),
  sq(21,'Which is an important part of the listening process during a client interview?',
    ['Acknowledging', 'Agreeing', 'Questioning', 'Speaking'],0,
    'Acknowledging that a message has been received and understood is a core part of active listening.'),
  sq(22,'Which would be regarded as a closed question?',
    ['How would you feel if your investments were to fall?', 'What are the most important things you would like me to address?', 'What would that mean to you?', 'When were you born?'],3,
    'A closed question seeks a specific fact or brief answer, like a date of birth.'),
  sq(23,'Phil purchased several products. Which will still be within the cancellation period 28 days after purchase?',
    ['A £500 contribution into a personal pension', 'A £5,100 payment into a stocks and shares ISA', 'A £10,000 lump-sum unit trust investment', 'A £50,000 investment into an OEIC'],0,
    'Pensions carry a 30-day cooling-off period, so 28 days after purchase is still within it — investments/ISAs/OEICs have only a 14-day period, already expired.'),
  sq(24,'Financial advisers must obtain a Statement of Professional Standing from an accredited body:',
    ['Annually', 'Every three years', 'Every five years', 'When they first achieve competent status only'],0,
    'The SPS must be renewed annually.'),
  sq(25,'Which ethical theory looks at the nature of moral judgements and does not consider whether anything is actually right or wrong?',
    ['Applied ethics', 'Deontological ethics', 'Meta-ethics', 'Natural ethics'],2,
    'Meta-ethics examines the nature of moral judgements themselves, rather than judging specific actions as right or wrong.'),
  sq(26,'(Case study: Excelsior Finance, compliance review) What is the most likely problem identified with the firm\u2019s financial promotions?',
    ['They warn that past performance is not necessarily a reliable indicator of future results', 'They use unsolicited mailshots to prospective clients', 'The use of past performance data in the promotions', 'They do not use comparisons with other companies\u2019 products'],2,
    'The way past performance data is presented (e.g. insufficiently prominent risk warnings, or too short a period) is the likely compliance issue flagged.'),
  sq(27,'The cold call team member\u2019s action breached FCA rules relating to calls about:',
    ['Life assurance', 'Unit trusts', 'Open ended investment companies', 'Mortgages'],3,
    'Unsolicited cold calling is specifically prohibited for mortgages (unlike packaged products such as life assurance and unit trusts).'),
  sq(28,'What is most likely the problem Davina identified with the firm\u2019s initial disclosure documentation?',
    ['The document is published on the firm\u2019s website', 'There is no information about the Financial Services Compensation Scheme', 'It includes information about how the firm evaluates investment performance', 'There is no information about the Financial Ombudsman Service'],1,
    'Missing FSCS compensation information is a required element of initial disclosure documentation.'),
  sq(29,'Regarding wills and trusts arranged by Excelsior\u2019s advisers as representatives of Gateway Wills and Trusts, which is true?',
    ['Excelsior Finance would be solely responsible for the adviser\u2019s conduct', 'Neither firm would be responsible', 'Gateway Wills and Trusts would be solely responsible for the adviser\u2019s conduct', 'Excelsior and Gateway would be jointly responsible'],2,
    'Acting as Gateway\u2019s representative for this specific activity makes Gateway responsible for that conduct.'),
  sq(30,'A colleague says Davina is wrong on one point of her robo-advice assessment. Davina is wrong in stating that:',
    ['The advice does not have to meet all the regulatory standards of normal advice', 'Although technology-based, the process can involve personal interaction with the adviser', 'Hybrid advice can be delivered online, over the phone or in person', 'Robo-advice could be used for other client needs'],0,
    'Robo-advice MUST meet the same regulatory suitability standards as traditional advice — Davina\u2019s statement to the contrary is the error.'),
  sq(31,'(Case study: divorcing clients Bob & Karen; Bob\u2019s mother gave him £100,000 two years before her death, in addition to leaving her estate) Which is true?',
    ['Martin should inform Bob he should declare the gift for inheritance tax purposes', 'Martin should notify his money-laundering reporting officer and ask for advice', 'Martin should tell Bob this will not affect the estate, as the gift was made two years ago', 'No additional inheritance tax will be charged'],0,
    'A gift made within 7 years of death remains potentially relevant for IHT (as a PET that has failed), so it should be declared.'),
  sq(32,'In respect of appropriate ethical standards, how should Martin proceed advising the divorcing Bob and Karen?',
    ['Advise Bob only, as he needs investment advice', 'Advise both clients and maintain a neutral position', 'Advise both clients, providing copies of all documentation to each', 'Recommend all advice be given only when both clients are present'],1,
    'Martin should advise both parties fairly and maintain a neutral position, given the conflict of interest inherent in a divorce situation.'),
  sq(33,'Martin needs up-to-date evidence of Bob\u2019s identity. Which of these are most likely acceptable: 1. Driving licence with photo, 2. Recent council tax bill, 3. Mobile phone bill, 4. Electoral roll entry?',
    ['1 and 2 only', '1, 2 and 3 only', '1, 2 and 4 only', '2, 3 and 4 only'],2,
    'A driving licence, council tax bill and electoral roll entry are all acceptable ID evidence — a mobile phone bill is specifically NOT acceptable.'),
  sq(34,'To obtain an annual SPS: 1. Detail training/development for a minimum of 21 hours, 2. Minimum of 35 hours, 3. Submitted to employer only, 4. Submitted to a recognised accredited body only. Which combination is correct?',
    ['1 and 3', '1 and 4', '2 and 4', '2 and 3'],2,
    'The SPS requires a minimum of 35 hours\u2019 CPD (of which 21 must be structured) and must be submitted to a recognised accredited body, not the employer.'),
  sq(35,'Martin is subject to the FCA\u2019s Certification Regime only. Which conduct rule does NOT apply to him?',
    ['Act with integrity', 'Act with due skill, care and diligence', 'Pay due regard to the interests of customers and treat them fairly', 'Take reasonable steps to ensure the business you are responsible for is controlled effectively'],3,
    'This is a senior manager-only conduct rule (SM1) — Martin, being subject only to the Certification Regime, is not bound by it.'),
  sq(36,'(Case study: Forward Financial Planning, rising complaints) To follow the correct complaints procedure, Peter should:',
    ['Acknowledge complaints within 5 days and resolve within 21 days', 'Make offers to settle before referring to the Ombudsman', 'Provide a final response letter within 8 weeks of receipt or explain the delay', 'Refer complaints to the Ombudsman if unresolved within 3 days'],2,
    'Firms must provide a final response within 8 weeks, or explain the delay and advise the customer of their right to go to the FOS.'),
  sq(37,'Alan takes his complaint to the FOS, who decide in his favour. Which is NOT within the range of compensation actions available?',
    ['Compensate for distress or inconvenience', 'Compensate for financial loss', 'Reimburse for costs and interest', 'Reimburse for lost growth on funds invested'],3,
    'Reimbursing hypothetical "lost growth" is not a standard FOS remedy — the aim is to put the customer back in their original position, not to guarantee investment gains.'),
  sq(38,'Peter wonders about Felicity\u2019s complaint validity, given advice was given more than 6 years ago. Which is true?',
    ['As she raised it directly with the firm, there is no time limit', 'As advice was given 8 years ago, she has left it two years too late', 'As she raised it within 3 years of becoming aware, it is valid', 'As it is about a mortgage, the time limit is 3 years from completion'],2,
    'The FOS time limit is 6 years from the event OR 3 years from becoming aware, whichever is later — Felicity\u2019s complaint is valid on the latter basis.'),
  sq(39,'What would prevent Johnson\u2019s Bakery Ltd taking their complaint to the FOS?',
    ['If its annual turnover is more than £6.5 million', 'If its net asset value is more than £5 million', 'The fact it has more than ten employees', 'The fact its complaint relates to pensions'],0,
    'FOS eligibility for small businesses requires turnover below £6.5 million (among other thresholds) — exceeding this excludes them.'),
  sq(40,'Records relating to the three complaints received this month should be retained for a minimum of:',
    ['At least one year', 'At least three years', 'At least six years', 'Indefinitely'],1,
    'Complaint records must be retained for at least 3 years from receipt.')
]
